/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java")
    id("maven-publish")
    id("com.gradleup.shadow") version "9.6.1"
    id("xyz.jpenilla.run-paper") version "3.1.0"
}

repositories {
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
    maven {
        name = "chamosmpRepoReleases"
        url = uri("https://maven.chamosmp.net/releases")
    }
    maven("https://eldonexus.de/repository/maven-public/")
    maven {
        url = uri("https://repo.extendedclip.com/releases/")
    }
    maven("https://nexus.scarsz.me/content/groups/public/")
    maven("https://repo.essentialsx.net/releases/")
    mavenCentral()
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.2.build.+")

    implementation("net.chamosmp.sqdlib:sqdlib-paper:2.1.2")

    // StrokkCommands
    compileOnly("net.strokkur.commands:annotations-paper:2.3.0")
    annotationProcessor("net.strokkur.commands:processor-paper:2.3.0")

    // Plugin Dependencies
    compileOnly("net.luckperms:api:5.5")
    compileOnly("me.clip:placeholderapi:2.12.3")

    // Discord Integration
    compileOnly("com.discordsrv:discordsrv:1.29.0")
    compileOnly("net.essentialsx:EssentialsX:2.21.2")
    compileOnly("net.essentialsx:EssentialsXDiscord:2.21.2")


    // Plugin Messaging
    compileOnly("io.lettuce:lettuce-core:7.7.0.RELEASE")
    compileOnly("io.nats:jnats:2.26.2")
    compileOnly("com.rabbitmq:amqp-client:5.35.0")
}

group = "net.chamosmp.irene"
version = "1.0.0"
description = "Irene, is a chat plugin, which extends to chat moderation, and linking chats between servers"
java.sourceCompatibility = JavaVersion.VERSION_25

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks {
    shadowJar {
        configurations = project.configurations.runtimeClasspath.map { setOf(it) }

        relocate("net.chamosmp.sqdlib", "net.chamosmp.irene.libs.sqdlib")
    }

    withType<JavaCompile> {
        options.encoding = "UTF-8"
    }
    withType<Javadoc> {
        options.encoding = "UTF-8"
    }

    processResources {
        val props = mapOf("version" to project.version, "description" to project.description)
        inputs.properties(props)
        filteringCharset = "UTF-8"

        filesMatching("paper-plugin.yml") {
            expand(props)
        }
    }

    runServer {
        downloadPlugins {
            modrinth("lKEzGugV", "2.12.3")
            modrinth("Vebnzrzj", "v5.5.53-bukkit")
            //modrinth("UmLGoGij", "1.30.5") // DiscordSRV
        }

        minecraftVersion("26.2")
    }
}