chat-formats:
  enabled: true

  formats: # All the groups you want. If the player's group isn't here it will default to default.
    default: "%prefix% <white>%name%<reset> <gray>» %message%"
    admin: "%prefix% <bold>%name%<reset> <gray>»</gray> <red>%message%"
    owner: "%prefix%<reset> %name%<reset>%suffix%<reset> <gray>»</gray> <rainbow>%message%"

chat-heads:
  enabled: true # Should it be enabled
  type: NAME # Available options: NAME, MESSAGE. Based on what you put, it will put the chat head before it.

# Available options:
# NON_INTERACTABLE, FORMATTED_TEXT, DEFAULT, anything else to disable
minimessage-formatting: false # WARNING. This may cause exploits in your server and make it easier for players to socially manipulate other players into running commands. If you want players to be able to use player head or such use "emojis"

emojis:
  enabled: true
  character: ":" # For example, if ":" is the value, it will look like :Chamogelastos:

  items: true # When true it will allow players to do something like :ender_pearl:, and replace it with the ender pearl texture. Needs the root enabled as true
  player-heads: true # When true it will allow players to do something like :Chamogelastos: and replace it with the player head of Chamogelastos. Needs the root enabled as true


priority: HIGHEST
debug: false

private-message:
  enabled: true # You need to restart the server for this to take place
  format: "<#FF00FF><b>MSG <reset>| <#FF00FF> %sending_player_you% to %receiving_player_you%</#FF00FF> > <#FF00FF>%message%" # The message format. If you see, the placeholders are ending in you, that means instead of showing the entire name, it'll if the player is you.
  player-not-online: "<gray>%player% is not online"

  you-string: "You"

  allow-players-to-self-message: true
  you-cannot-message-yourself: "<red>You cannot message yourself!" # Needs the above option disabled

  name: "msg"
  aliases:
    - w
    - message
    - whisper
  respond:
    enabled: true
    not-in-conversation: "<red>You are not in a conversation!"

    name: "r"
    aliases:
      - "respond"

pings:
  enabled: false
  ping-character: "@"
  color: "<gold>" # What mini message color should the ping have?
  sound:
    name: 'NOTE_BLOCK_BELL' # The sound to play, to the player being pinged. Find a value here: https://jd.papermc.io/paper/26.2/org/bukkit/Sound.html and remove the first prefix
    volume: 100
    pitch: 100

messaging:
  enabled: false

  database: REDIS # Available types: REDIS, NATS, RABBITMQ

  host: "localhost"
  port: "6379"

  password: null # Not used in NATS
  rabbitmq-user: "" # RabbitMQ Only

discord-integration: # Requires discordsrv or essentialsxdiscord (WARNING: Not Tested!)
  enabled: false

  # Available placeholders:
  # sender, message, channel
  mc-format: "<blue>Discord <reset>| %sender% > %message%"

first-join-message:
  enabled: true

  messages: # Available placeholders: name, prefix, suffix
    - "<aqua>Welcome to the server!"
    - "<aqua>We have a friendly community"

join-message: # Messages a player on join
  enabled: true

  send-on-first-join: false # Can be used to resolve conflicts with "first-join-message"

  messages: # Available placeholders: name, prefix, suffix
    - "<aqua>Welcome back %name%"

join-and-leave-messages:
  enabled: true

  # Available placeholders: name, prefix, suffix
  join: "<yellow>%name% joined the game"
  leave: "<yellow>%name% left the game"

messages:
  reloaded: "<green>Irene Reloaded."